[package]
name = "kvdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "~1.0.126"
serde_derive = "~1.0.126"
sqlparser = "0.11"
bincode = "~1.3.3"
derivative = "~2.2.0"
